name: todo
description: The main purpose of this application is to allow users to create, organize and track their daily tasks efficiently.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  simple_moment: ^1.1.1
  sqflite: ^2.2.8+4
  flutter_local_notifications:
  flutter_bloc:
  bloc:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # 
  assets:
    - images/
  # 
  fonts:
    - family: Dancing
      fonts:
        - asset: font/dancing.ttf
    - family: Roboto
      fonts:
        - asset: font/roboto.ttf
